version: "3.9" 
services:
  web:
    build: .
    ports:
      - "23780:3000"
    volumes:
      - ./src:/app/src
      - logvolume:/var/log
    command: npm run start
    env_file: .env
volumes:
  logvolume: {}